# Generated by Django 4.2.6 on 2023-11-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choice_cho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cho',
            new_name='Choice',
        ),
    ]
