# Generated by Django 4.2.6 on 2023-11-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Cho',
        ),
    ]
